def show_error_log():
    print("This is an error log...")
    print("Something went wrong. Please enter \"python main.py -help\" to show all the parameters.")

def show_help_information():
    print("Welcome to the Data Generator v1.0.0")
    print()
    print("To use Data Generator, you should enter like this:")
    print()
    print("    python main.py [number_of_person_data_lines] <output_format>")
    print()
    print("[number_of_person_data_lines] possible values:")
    print("    Any integer number greater than 0")
    print()
    print("<output_format> possible values:")
    print("    -json: For JSON")
    print("    -csv: For CSV")
    print("    -sql: For SQL insert")
    print()
    print("Developers:")
    print("    Gabriel Sena San Martin, Gabriel Alexander Farias, Gonzalo Ivan Santos Portales")
    print("    Helder Melik Schramm, João Vítor Câmara")
    print()
    print("MIT license")